// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9sKmrPAidYpILOvI2VvgacFL2rzguRtQ',
    appId: '1:162229109465:web:9ff7ff6b2463fc2ea874c8',
    messagingSenderId: '162229109465',
    projectId: 'project-8402850690952052893',
    authDomain: 'project-8402850690952052893.firebaseapp.com',
    storageBucket: 'project-8402850690952052893.firebasestorage.app',
    measurementId: 'G-YRVTDEM92W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6zuFeNDOns0JJzHKjL4I3CH1a2P0OT9g',
    appId: '1:162229109465:android:9b37dd250bf9c0b6a874c8',
    messagingSenderId: '162229109465',
    projectId: 'project-8402850690952052893',
    storageBucket: 'project-8402850690952052893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4kGGlbHuFJNv3LzpBvPODucEItzNeusY',
    appId: '1:162229109465:ios:04e54f16bba62196a874c8',
    messagingSenderId: '162229109465',
    projectId: 'project-8402850690952052893',
    storageBucket: 'project-8402850690952052893.firebasestorage.app',
    iosBundleId: 'com.example.production',
  );
}
